### PR TITLE
Rename OKTA into Okta into documentation

### PR DESCRIPTION
**Pull request by gabrielsroka**
It's "Okta", not "OKTA".

Is this an Official Okta package?

### CODE REVIEW

**Comment by Colin-b** [comment]
Hi Gabriel,

First of, thanks a lot for those changes.

This is not an official Okta package, but it was implemented following Okta specifications and it is currently in use (to my knowledge) within Engie to manage Okta authentication.

If you do have some Okta contacts I would gladly reach out to have some stamp of approval if it makes you more confident in this package :-)

**Comment by rdegges** [comment]
Hey @Colin-b -- I work at Okta =) I'd love to give it an official stamp of approval! How can I help?

PS: This is really awesome. @gabrielsroka brought it to my attention, hadn't seen it before. <3

**Comment by Colin-b** [comment]
Hi @rdegges ,

That's great to hear!

I don't know if there is a process in place @ Okta but I see that there is [a page](https://developer.okta.com/code/python/) where developers can find python resources.

I guess a link here would do the trick :)

Also if you (or @gabrielsroka ) feel like the samples in the documentation can be somehow enhanced to lower the entry cost for newcomers, any input would be great

In addition, would you mind updating the README with a testimonial section containing one or two short sentences about your feeling on this package?

This stuff helps build confidence I guess.

Thanks again

**Comment by rdegges** [comment]
Yo! I just sent a PR with an endorsement. I'll also contribute some more when I get some time here =D

RE: getting it linked on the website, I'm working on that now! =)

**Pull request merged**
